server
{
	listen 443 ssl;
	listen [::]:443 ssl;
	#Domain defined in the .env
	server_name ${DOMAIN};
	#SSL config using TLSv1.2 and TLSv1.3 only, and ciphers
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/ssl/certs/nginx.crt;
	ssl_certificate_key /etc/ssl/private/nginx.key;
	ssl_prefer_server_ciphers on;
	#Root directory
	root /var/www/html;
	index index.php index.html;

	#Location for PHP files, using FastCGI to communicate with PHP-FPM
	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ /\.{
		deny all;
		acess_log off;
		log_not_found off;
	}
}
